// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_extract_motif_candidates
Rcpp::List cpp_extract_motif_candidates(Rcpp::List contexts, Rcpp::List roots, double max_size, bool branches);
RcppExport SEXP _glymotif_cpp_extract_motif_candidates(SEXP contextsSEXP, SEXP rootsSEXP, SEXP max_sizeSEXP, SEXP branchesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type contexts(contextsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type roots(rootsSEXP);
    Rcpp::traits::input_parameter< double >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type branches(branchesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_motif_candidates(contexts, roots, max_size, branches));
    return rcpp_result_gen;
END_RCPP
}
// cpp_match_structures
SEXP cpp_match_structures(SEXP glycans, SEXP motifs, DataFrame dictionary, CharacterVector alignments, bool ignore_linkages, bool strict_sub, bool lenient, List degrees, const std::string& output, bool strict_floating, int maximum);
RcppExport SEXP _glymotif_cpp_match_structures(SEXP glycansSEXP, SEXP motifsSEXP, SEXP dictionarySEXP, SEXP alignmentsSEXP, SEXP ignore_linkagesSEXP, SEXP strict_subSEXP, SEXP lenientSEXP, SEXP degreesSEXP, SEXP outputSEXP, SEXP strict_floatingSEXP, SEXP maximumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type glycans(glycansSEXP);
    Rcpp::traits::input_parameter< SEXP >::type motifs(motifsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dictionary(dictionarySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type alignments(alignmentsSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_linkages(ignore_linkagesSEXP);
    Rcpp::traits::input_parameter< bool >::type strict_sub(strict_subSEXP);
    Rcpp::traits::input_parameter< bool >::type lenient(lenientSEXP);
    Rcpp::traits::input_parameter< List >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< bool >::type strict_floating(strict_floatingSEXP);
    Rcpp::traits::input_parameter< int >::type maximum(maximumSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_match_structures(glycans, motifs, dictionary, alignments, ignore_linkages, strict_sub, lenient, degrees, output, strict_floating, maximum));
    return rcpp_result_gen;
END_RCPP
}
// cpp_vf2_subgraph_mono
Rcpp::List cpp_vf2_subgraph_mono(int glycan_vertex_count, Rcpp::IntegerMatrix glycan_edges, int motif_vertex_count, Rcpp::IntegerMatrix motif_edges, Rcpp::LogicalMatrix vertex_compatibility, Rcpp::LogicalMatrix edge_compatibility, bool first_only, bool unique_vertex_sets);
RcppExport SEXP _glymotif_cpp_vf2_subgraph_mono(SEXP glycan_vertex_countSEXP, SEXP glycan_edgesSEXP, SEXP motif_vertex_countSEXP, SEXP motif_edgesSEXP, SEXP vertex_compatibilitySEXP, SEXP edge_compatibilitySEXP, SEXP first_onlySEXP, SEXP unique_vertex_setsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type glycan_vertex_count(glycan_vertex_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type glycan_edges(glycan_edgesSEXP);
    Rcpp::traits::input_parameter< int >::type motif_vertex_count(motif_vertex_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type motif_edges(motif_edgesSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type vertex_compatibility(vertex_compatibilitySEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type edge_compatibility(edge_compatibilitySEXP);
    Rcpp::traits::input_parameter< bool >::type first_only(first_onlySEXP);
    Rcpp::traits::input_parameter< bool >::type unique_vertex_sets(unique_vertex_setsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_vf2_subgraph_mono(glycan_vertex_count, glycan_edges, motif_vertex_count, motif_edges, vertex_compatibility, edge_compatibility, first_only, unique_vertex_sets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glymotif_cpp_extract_motif_candidates", (DL_FUNC) &_glymotif_cpp_extract_motif_candidates, 4},
    {"_glymotif_cpp_match_structures", (DL_FUNC) &_glymotif_cpp_match_structures, 11},
    {"_glymotif_cpp_vf2_subgraph_mono", (DL_FUNC) &_glymotif_cpp_vf2_subgraph_mono, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_glymotif(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
