# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_vf2_subgraph_mono <- function(glycan_vertex_count, glycan_edges, motif_vertex_count, motif_edges, vertex_compatibility, edge_compatibility, first_only, unique_vertex_sets) {
    .Call(`_glymotif_cpp_vf2_subgraph_mono`, glycan_vertex_count, glycan_edges, motif_vertex_count, motif_edges, vertex_compatibility, edge_compatibility, first_only, unique_vertex_sets)
}

